# Generated by Django 3.2.7 on 2021-10-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211017_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
