version: '3.1'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: bash -c "
      python manage.py migrate
      && python manage.py fill_db
      && gunicorn geekshop.wsgi:application --bind 0.0.0.0:8000
      "
    expose:
      - 8000
    volumes:
      - static_volume:/home/GB_Django/web/static
      - media_volume:/home/GB_Django/web/media
    env_file:
      - ./geekshop/.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./geekshop/.env.prod.db
  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    volumes:
      - static_volume:/home/GB_Django/web/static
      - media_volume:/home/GB_Django/web/media
    depends_on:
      - web

volumes:
    postgres_volume:
    static_volume:
    media_volume: