# Generated by Django 3.2.7 on 2021-11-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
